name: Auto-assign new pull requests

on:
  pull_request_target:
    types: [opened]

permissions:
  issues: write

jobs:
  assign:
    name: Assign repository owner
    runs-on: ubuntu-latest
    steps:
      - name: Assign repository owner
        uses: kentaro-m/auto-assign-action@v2.0.2
